name: NAGADHAT API PRODUCTION DEPLOYMENT

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          # host: ${{ secrets.NAGADHAT_PROD_HOST }}
          # username: ${{ secrets.NAGADHAT_PROD_USER }}
          # port: ${{ secrets.NAGADHAT_PROD_PORT }}
          # password: ${{ secrets.NAGADHAT_PROD_PASS }}
          KEY: ${{ secrets.NAGADHAT_PROD_SSH_SECRET_KEY }}
          source: "."
          target: "/home/nagadhat/public_html/live-api"

      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          # host: ${{ secrets.NAGADHAT_PROD_HOST }}
          # username: ${{ secrets.NAGADHAT_PROD_USER }}
          # port: ${{ secrets.NAGADHAT_PROD_PORT }}
          # password: ${{ secrets.NAGADHAT_PROD_PASS }}
          KEY: ${{ secrets.NAGADHAT_PROD_SSH_SECRET_KEY }}
          script: |
            # cd /home/nagadhat/public_html/live-api
            cd /home/nagadhat/public_html/live-api
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            echo "Generating key..."
            php artisan key:generate
            echo "Granting directory permissions..."
            chmod -R 777 bootstrap/
            chmod -R 777 storage/
            #echo "running migration"
            #php artisan migrate
            #echo "run seed"
            #php artisan db:seed
            #echo "finally unit testing..."
            #vendor/bin/phpunit
            #echo "executing yarn command"
            #echo  yarn && yarn run prod
            echo "done...."
